// Package api provides primitives to interact with the openapi HTTP API.
//
// Code generated by github.com/deepmap/oapi-codegen version v1.12.4 DO NOT EDIT.
package api

import (
	"bytes"
	"compress/gzip"
	"context"
	"encoding/base64"
	"encoding/json"
	"fmt"
	"io"
	"net/http"
	"net/url"
	"path"
	"strings"

	"github.com/deepmap/oapi-codegen/pkg/runtime"
	"github.com/getkin/kin-openapi/openapi3"
	"github.com/labstack/echo/v4"
)

// ErrorReponse defines model for ErrorReponse.
type ErrorReponse struct {
	// Message Error message
	Message string `json:"message"`

	// Status Status
	Status string `json:"status"`
}

// StatusOnlyReponse defines model for StatusOnlyReponse.
type StatusOnlyReponse struct {
	// Status Status
	Status string `json:"status"`
}

// RequestEditorFn  is the function signature for the RequestEditor callback function
type RequestEditorFn func(ctx context.Context, req *http.Request) error

// Doer performs HTTP requests.
//
// The standard http.Client implements this interface.
type HttpRequestDoer interface {
	Do(req *http.Request) (*http.Response, error)
}

// Client which conforms to the OpenAPI3 specification for this service.
type Client struct {
	// The endpoint of the server conforming to this interface, with scheme,
	// https://api.deepmap.com for example. This can contain a path relative
	// to the server, such as https://api.deepmap.com/dev-test, and all the
	// paths in the swagger spec will be appended to the server.
	Server string

	// Doer for performing requests, typically a *http.Client with any
	// customized settings, such as certificate chains.
	Client HttpRequestDoer

	// A list of callbacks for modifying requests which are generated before sending over
	// the network.
	RequestEditors []RequestEditorFn
}

// ClientOption allows setting custom parameters during construction
type ClientOption func(*Client) error

// Creates a new Client, with reasonable defaults
func NewClient(server string, opts ...ClientOption) (*Client, error) {
	// create a client with sane default values
	client := Client{
		Server: server,
	}
	// mutate client and add all optional params
	for _, o := range opts {
		if err := o(&client); err != nil {
			return nil, err
		}
	}
	// ensure the server URL always has a trailing slash
	if !strings.HasSuffix(client.Server, "/") {
		client.Server += "/"
	}
	// create httpClient, if not already present
	if client.Client == nil {
		client.Client = &http.Client{}
	}
	return &client, nil
}

// WithHTTPClient allows overriding the default Doer, which is
// automatically created using http.Client. This is useful for tests.
func WithHTTPClient(doer HttpRequestDoer) ClientOption {
	return func(c *Client) error {
		c.Client = doer
		return nil
	}
}

// WithRequestEditorFn allows setting up a callback function, which will be
// called right before sending the request. This can be used to mutate the request.
func WithRequestEditorFn(fn RequestEditorFn) ClientOption {
	return func(c *Client) error {
		c.RequestEditors = append(c.RequestEditors, fn)
		return nil
	}
}

// The interface specification for the client above.
type ClientInterface interface {
	// GetV1HealthReadyz request
	GetV1HealthReadyz(ctx context.Context, reqEditors ...RequestEditorFn) (*http.Response, error)

	// PostV1RepoSubscribeProviderGroupRepo request
	PostV1RepoSubscribeProviderGroupRepo(ctx context.Context, provider string, group string, repo string, reqEditors ...RequestEditorFn) (*http.Response, error)
}

func (c *Client) GetV1HealthReadyz(ctx context.Context, reqEditors ...RequestEditorFn) (*http.Response, error) {
	req, err := NewGetV1HealthReadyzRequest(c.Server)
	if err != nil {
		return nil, err
	}
	req = req.WithContext(ctx)
	if err := c.applyEditors(ctx, req, reqEditors); err != nil {
		return nil, err
	}
	return c.Client.Do(req)
}

func (c *Client) PostV1RepoSubscribeProviderGroupRepo(ctx context.Context, provider string, group string, repo string, reqEditors ...RequestEditorFn) (*http.Response, error) {
	req, err := NewPostV1RepoSubscribeProviderGroupRepoRequest(c.Server, provider, group, repo)
	if err != nil {
		return nil, err
	}
	req = req.WithContext(ctx)
	if err := c.applyEditors(ctx, req, reqEditors); err != nil {
		return nil, err
	}
	return c.Client.Do(req)
}

// NewGetV1HealthReadyzRequest generates requests for GetV1HealthReadyz
func NewGetV1HealthReadyzRequest(server string) (*http.Request, error) {
	var err error

	serverURL, err := url.Parse(server)
	if err != nil {
		return nil, err
	}

	operationPath := fmt.Sprintf("/v1/health/readyz")
	if operationPath[0] == '/' {
		operationPath = "." + operationPath
	}

	queryURL, err := serverURL.Parse(operationPath)
	if err != nil {
		return nil, err
	}

	req, err := http.NewRequest("GET", queryURL.String(), nil)
	if err != nil {
		return nil, err
	}

	return req, nil
}

// NewPostV1RepoSubscribeProviderGroupRepoRequest generates requests for PostV1RepoSubscribeProviderGroupRepo
func NewPostV1RepoSubscribeProviderGroupRepoRequest(server string, provider string, group string, repo string) (*http.Request, error) {
	var err error

	var pathParam0 string

	pathParam0, err = runtime.StyleParamWithLocation("simple", false, "provider", runtime.ParamLocationPath, provider)
	if err != nil {
		return nil, err
	}

	var pathParam1 string

	pathParam1, err = runtime.StyleParamWithLocation("simple", false, "group", runtime.ParamLocationPath, group)
	if err != nil {
		return nil, err
	}

	var pathParam2 string

	pathParam2, err = runtime.StyleParamWithLocation("simple", false, "repo", runtime.ParamLocationPath, repo)
	if err != nil {
		return nil, err
	}

	serverURL, err := url.Parse(server)
	if err != nil {
		return nil, err
	}

	operationPath := fmt.Sprintf("/v1/repo/subscribe/%s/%s/%s", pathParam0, pathParam1, pathParam2)
	if operationPath[0] == '/' {
		operationPath = "." + operationPath
	}

	queryURL, err := serverURL.Parse(operationPath)
	if err != nil {
		return nil, err
	}

	req, err := http.NewRequest("POST", queryURL.String(), nil)
	if err != nil {
		return nil, err
	}

	return req, nil
}

func (c *Client) applyEditors(ctx context.Context, req *http.Request, additionalEditors []RequestEditorFn) error {
	for _, r := range c.RequestEditors {
		if err := r(ctx, req); err != nil {
			return err
		}
	}
	for _, r := range additionalEditors {
		if err := r(ctx, req); err != nil {
			return err
		}
	}
	return nil
}

// ClientWithResponses builds on ClientInterface to offer response payloads
type ClientWithResponses struct {
	ClientInterface
}

// NewClientWithResponses creates a new ClientWithResponses, which wraps
// Client with return type handling
func NewClientWithResponses(server string, opts ...ClientOption) (*ClientWithResponses, error) {
	client, err := NewClient(server, opts...)
	if err != nil {
		return nil, err
	}
	return &ClientWithResponses{client}, nil
}

// WithBaseURL overrides the baseURL.
func WithBaseURL(baseURL string) ClientOption {
	return func(c *Client) error {
		newBaseURL, err := url.Parse(baseURL)
		if err != nil {
			return err
		}
		c.Server = newBaseURL.String()
		return nil
	}
}

// ClientWithResponsesInterface is the interface specification for the client with responses above.
type ClientWithResponsesInterface interface {
	// GetV1HealthReadyz request
	GetV1HealthReadyzWithResponse(ctx context.Context, reqEditors ...RequestEditorFn) (*GetV1HealthReadyzResponse, error)

	// PostV1RepoSubscribeProviderGroupRepo request
	PostV1RepoSubscribeProviderGroupRepoWithResponse(ctx context.Context, provider string, group string, repo string, reqEditors ...RequestEditorFn) (*PostV1RepoSubscribeProviderGroupRepoResponse, error)
}

type GetV1HealthReadyzResponse struct {
	Body         []byte
	HTTPResponse *http.Response
}

// Status returns HTTPResponse.Status
func (r GetV1HealthReadyzResponse) Status() string {
	if r.HTTPResponse != nil {
		return r.HTTPResponse.Status
	}
	return http.StatusText(0)
}

// StatusCode returns HTTPResponse.StatusCode
func (r GetV1HealthReadyzResponse) StatusCode() int {
	if r.HTTPResponse != nil {
		return r.HTTPResponse.StatusCode
	}
	return 0
}

type PostV1RepoSubscribeProviderGroupRepoResponse struct {
	Body         []byte
	HTTPResponse *http.Response
	JSON201      *StatusOnlyReponse
	JSON400      *ErrorReponse
}

// Status returns HTTPResponse.Status
func (r PostV1RepoSubscribeProviderGroupRepoResponse) Status() string {
	if r.HTTPResponse != nil {
		return r.HTTPResponse.Status
	}
	return http.StatusText(0)
}

// StatusCode returns HTTPResponse.StatusCode
func (r PostV1RepoSubscribeProviderGroupRepoResponse) StatusCode() int {
	if r.HTTPResponse != nil {
		return r.HTTPResponse.StatusCode
	}
	return 0
}

// GetV1HealthReadyzWithResponse request returning *GetV1HealthReadyzResponse
func (c *ClientWithResponses) GetV1HealthReadyzWithResponse(ctx context.Context, reqEditors ...RequestEditorFn) (*GetV1HealthReadyzResponse, error) {
	rsp, err := c.GetV1HealthReadyz(ctx, reqEditors...)
	if err != nil {
		return nil, err
	}
	return ParseGetV1HealthReadyzResponse(rsp)
}

// PostV1RepoSubscribeProviderGroupRepoWithResponse request returning *PostV1RepoSubscribeProviderGroupRepoResponse
func (c *ClientWithResponses) PostV1RepoSubscribeProviderGroupRepoWithResponse(ctx context.Context, provider string, group string, repo string, reqEditors ...RequestEditorFn) (*PostV1RepoSubscribeProviderGroupRepoResponse, error) {
	rsp, err := c.PostV1RepoSubscribeProviderGroupRepo(ctx, provider, group, repo, reqEditors...)
	if err != nil {
		return nil, err
	}
	return ParsePostV1RepoSubscribeProviderGroupRepoResponse(rsp)
}

// ParseGetV1HealthReadyzResponse parses an HTTP response from a GetV1HealthReadyzWithResponse call
func ParseGetV1HealthReadyzResponse(rsp *http.Response) (*GetV1HealthReadyzResponse, error) {
	bodyBytes, err := io.ReadAll(rsp.Body)
	defer func() { _ = rsp.Body.Close() }()
	if err != nil {
		return nil, err
	}

	response := &GetV1HealthReadyzResponse{
		Body:         bodyBytes,
		HTTPResponse: rsp,
	}

	return response, nil
}

// ParsePostV1RepoSubscribeProviderGroupRepoResponse parses an HTTP response from a PostV1RepoSubscribeProviderGroupRepoWithResponse call
func ParsePostV1RepoSubscribeProviderGroupRepoResponse(rsp *http.Response) (*PostV1RepoSubscribeProviderGroupRepoResponse, error) {
	bodyBytes, err := io.ReadAll(rsp.Body)
	defer func() { _ = rsp.Body.Close() }()
	if err != nil {
		return nil, err
	}

	response := &PostV1RepoSubscribeProviderGroupRepoResponse{
		Body:         bodyBytes,
		HTTPResponse: rsp,
	}

	switch {
	case strings.Contains(rsp.Header.Get("Content-Type"), "json") && rsp.StatusCode == 201:
		var dest StatusOnlyReponse
		if err := json.Unmarshal(bodyBytes, &dest); err != nil {
			return nil, err
		}
		response.JSON201 = &dest

	case strings.Contains(rsp.Header.Get("Content-Type"), "json") && rsp.StatusCode == 400:
		var dest ErrorReponse
		if err := json.Unmarshal(bodyBytes, &dest); err != nil {
			return nil, err
		}
		response.JSON400 = &dest

	}

	return response, nil
}

// ServerInterface represents all server handlers.
type ServerInterface interface {
	// Check if the API is ready
	// (GET /v1/health/readyz)
	GetV1HealthReadyz(ctx echo.Context) error
	// Subscribe to a repository
	// (POST /v1/repo/subscribe/{provider}/{group}/{repo})
	PostV1RepoSubscribeProviderGroupRepo(ctx echo.Context, provider string, group string, repo string) error
}

// ServerInterfaceWrapper converts echo contexts to parameters.
type ServerInterfaceWrapper struct {
	Handler ServerInterface
}

// GetV1HealthReadyz converts echo context to params.
func (w *ServerInterfaceWrapper) GetV1HealthReadyz(ctx echo.Context) error {
	var err error

	// Invoke the callback with all the unmarshalled arguments
	err = w.Handler.GetV1HealthReadyz(ctx)
	return err
}

// PostV1RepoSubscribeProviderGroupRepo converts echo context to params.
func (w *ServerInterfaceWrapper) PostV1RepoSubscribeProviderGroupRepo(ctx echo.Context) error {
	var err error
	// ------------- Path parameter "provider" -------------
	var provider string

	err = runtime.BindStyledParameterWithLocation("simple", false, "provider", runtime.ParamLocationPath, ctx.Param("provider"), &provider)
	if err != nil {
		return echo.NewHTTPError(http.StatusBadRequest, fmt.Sprintf("Invalid format for parameter provider: %s", err))
	}

	// ------------- Path parameter "group" -------------
	var group string

	err = runtime.BindStyledParameterWithLocation("simple", false, "group", runtime.ParamLocationPath, ctx.Param("group"), &group)
	if err != nil {
		return echo.NewHTTPError(http.StatusBadRequest, fmt.Sprintf("Invalid format for parameter group: %s", err))
	}

	// ------------- Path parameter "repo" -------------
	var repo string

	err = runtime.BindStyledParameterWithLocation("simple", false, "repo", runtime.ParamLocationPath, ctx.Param("repo"), &repo)
	if err != nil {
		return echo.NewHTTPError(http.StatusBadRequest, fmt.Sprintf("Invalid format for parameter repo: %s", err))
	}

	// Invoke the callback with all the unmarshalled arguments
	err = w.Handler.PostV1RepoSubscribeProviderGroupRepo(ctx, provider, group, repo)
	return err
}

// This is a simple interface which specifies echo.Route addition functions which
// are present on both echo.Echo and echo.Group, since we want to allow using
// either of them for path registration
type EchoRouter interface {
	CONNECT(path string, h echo.HandlerFunc, m ...echo.MiddlewareFunc) *echo.Route
	DELETE(path string, h echo.HandlerFunc, m ...echo.MiddlewareFunc) *echo.Route
	GET(path string, h echo.HandlerFunc, m ...echo.MiddlewareFunc) *echo.Route
	HEAD(path string, h echo.HandlerFunc, m ...echo.MiddlewareFunc) *echo.Route
	OPTIONS(path string, h echo.HandlerFunc, m ...echo.MiddlewareFunc) *echo.Route
	PATCH(path string, h echo.HandlerFunc, m ...echo.MiddlewareFunc) *echo.Route
	POST(path string, h echo.HandlerFunc, m ...echo.MiddlewareFunc) *echo.Route
	PUT(path string, h echo.HandlerFunc, m ...echo.MiddlewareFunc) *echo.Route
	TRACE(path string, h echo.HandlerFunc, m ...echo.MiddlewareFunc) *echo.Route
}

// RegisterHandlers adds each server route to the EchoRouter.
func RegisterHandlers(router EchoRouter, si ServerInterface) {
	RegisterHandlersWithBaseURL(router, si, "")
}

// Registers handlers, and prepends BaseURL to the paths, so that the paths
// can be served under a prefix.
func RegisterHandlersWithBaseURL(router EchoRouter, si ServerInterface, baseURL string) {

	wrapper := ServerInterfaceWrapper{
		Handler: si,
	}

	router.GET(baseURL+"/v1/health/readyz", wrapper.GetV1HealthReadyz)
	router.POST(baseURL+"/v1/repo/subscribe/:provider/:group/:repo", wrapper.PostV1RepoSubscribeProviderGroupRepo)

}

// Base64 encoded, gzipped, json marshaled Swagger object
var swaggerSpec = []string{

	"H4sIAAAAAAAC/6xVwVLjOBD9FVXvHl12AuwefNtlKIbD1KQyFBfgoMidWGBLQt3OTCaVf59qGQeCoYaq",
	"4eZIr1+/Vr/ubMH4NniHjgnKLZCpsdXp8yxGH+cYvCOU3yH6gJEtptsWifQqXVRIJtrA1jso+zA1XGfA",
	"m4BQAnG0bgW7DIg1dzQO/NafjyJ2GUR86GzECsrrITzbK7jdR/jFHRqWHD3XV9ds3izgY2SMkwvQuqUX",
	"ZuMda8Py6XQrqFmjeeljqy5Rt5BBFxsooWYOVBbFGjEg5tRoc58b3xY6mtqukYrTsy/nR/9PT/6V6g4F",
	"X9aW1H+zC4U/gickJR2NWKMju2hQaVcp6xibxq7QsRJxsdUSTco71Qun7MYRmi5a3mTKeLe0K6W7yjLl",
	"eX7j5EEsN1LDHBvUhOoyanOPMeX+5E3XouNECxmsMVIvb5pP8omo9gGdDhZKOM6n+QQyCJrr1IFiPS1q",
	"1A3XRURdbX7K4QrTw0nPEutFBSWcI19NPyfovEdKWyj1OFEdTSbjnopCSypxi5R/JsdvgpznAShm7dpW",
	"xw2UcFqjuVd2qbhGdUi4y1IFEYMvqFsI6QKLbYh+bSuMu2K7ir4Lu2IrkF3yoid+xXtDsGKvtBI0WfZx",
	"o75brtXKrtGpgTZTiTX19wkJ2YsXm3niq6mMwZ599shwLvFyk3oRdYuMkaC83o4shvu0yvdPcJDSCkra",
	"Cdng9AEPz+eGY4fZ45KR8kcz9lrmvsx3pk3gP8/5uzSxf7X3Z7kd+XQ6bAh0yQo6hMaa1LjijkTJ9hnf",
	"3xGXUMJfxdO+Lh6XdTHedmkLHVY1fzLT3qOVDMNJPzEfouTgP+MVERdurRsrfn3okPjFiL1pf6Ha/QoA",
	"AP//6Ee18qsGAAA=",
}

// GetSwagger returns the content of the embedded swagger specification file
// or error if failed to decode
func decodeSpec() ([]byte, error) {
	zipped, err := base64.StdEncoding.DecodeString(strings.Join(swaggerSpec, ""))
	if err != nil {
		return nil, fmt.Errorf("error base64 decoding spec: %s", err)
	}
	zr, err := gzip.NewReader(bytes.NewReader(zipped))
	if err != nil {
		return nil, fmt.Errorf("error decompressing spec: %s", err)
	}
	var buf bytes.Buffer
	_, err = buf.ReadFrom(zr)
	if err != nil {
		return nil, fmt.Errorf("error decompressing spec: %s", err)
	}

	return buf.Bytes(), nil
}

var rawSpec = decodeSpecCached()

// a naive cached of a decoded swagger spec
func decodeSpecCached() func() ([]byte, error) {
	data, err := decodeSpec()
	return func() ([]byte, error) {
		return data, err
	}
}

// Constructs a synthetic filesystem for resolving external references when loading openapi specifications.
func PathToRawSpec(pathToFile string) map[string]func() ([]byte, error) {
	var res = make(map[string]func() ([]byte, error))
	if len(pathToFile) > 0 {
		res[pathToFile] = rawSpec
	}

	return res
}

// GetSwagger returns the Swagger specification corresponding to the generated code
// in this file. The external references of Swagger specification are resolved.
// The logic of resolving external references is tightly connected to "import-mapping" feature.
// Externally referenced files must be embedded in the corresponding golang packages.
// Urls can be supported but this task was out of the scope.
func GetSwagger() (swagger *openapi3.T, err error) {
	var resolvePath = PathToRawSpec("")

	loader := openapi3.NewLoader()
	loader.IsExternalRefsAllowed = true
	loader.ReadFromURIFunc = func(loader *openapi3.Loader, url *url.URL) ([]byte, error) {
		var pathToFile = url.String()
		pathToFile = path.Clean(pathToFile)
		getSpec, ok := resolvePath[pathToFile]
		if !ok {
			err1 := fmt.Errorf("path not found: %s", pathToFile)
			return nil, err1
		}
		return getSpec()
	}
	var specData []byte
	specData, err = rawSpec()
	if err != nil {
		return
	}
	swagger, err = loader.LoadFromData(specData)
	if err != nil {
		return
	}
	return
}
